Running the RICE base model with the flags: --n='witch17' --cooperation=coop --gamma=(...) --nameout=(...) 

```{r}
library(gdxtools)
library(tidyverse)

#mygdx <- gdx('results/results_witch17_reg.gdx')
#emi <- mygdx["E"] |> as_tibble() # see as table

var = 'E'  #'E' for emissions, 'TEMP_REGION' for temp

myfiles = file.path('results/Effort sharing scenarios/Budget 1000',c("results_approach_percapita_ssp2_1000.gdx","results_approach_gdp_percapita_inv_ssp2_1000.gdx","results_approach_hist_emis_inv_ssp2_1000.gdx","results_approach_current_emis_percapita_ssp2_1000.gdx"))
#
emi = batch_extract(var,files = myfiles)[[1]]

emi <- emi |>
  mutate(year = as.numeric(t) * 5 + 2010) |> # Transform time period into year
  #mutate(value = value*5) |>
  mutate(scen = basename(gdx)) |>            # Transform the filename into a scenario name
  mutate(scen = str_replace(scen, "_ssp2_1000.gdx", "")) |>
  mutate(scen = str_replace(scen, "results_", "")) |>
  mutate(scen = str_replace(scen, "approach_", "")) |>
  mutate(scen = str_replace(scen, "gdp_percapita_inv", "Ability to pay")) |>
  mutate(scen = str_replace(scen, "hist_emis_inv", "Equal cumulative emissions")) |>
  mutate(scen = str_replace(scen, "current_emis_percapita", "Grandfathering")) |>
  mutate(scen = str_replace(scen, "percapita", "Per capita"))
emi
```

# Maps

## Map codes

```{r}
# import the WITCH model regional definition
wreg <- read_csv('maped57.csv')

# Country name tools
library(countrycode)

# transforms ISO codes into country names
wreg <- wreg |>
mutate(region = countrycode(ISO, origin = 'iso3c', destination = 'country.name'))

wreg
```

Merging

```{r}
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)

world <- ne_countries(scale = "small", returnclass = "sf")
world <- subset(world,!adm0_a3 %in% c("ATA","FJI"))

# merge the WITCH regional definition with the world map
world <- merge(world,wreg, by.x = "adm0_a3", by.y = "ISO")

# merge with the emission data.frame
world0 <- merge(world,emi |> filter(year==2100), by = "n", allow.cartesian=TRUE)

# Use a better projection 'equal projection'
target_crs <- '+proj=eqearth +wktext'
world1 <- st_transform(world0, crs = target_crs)
```

##Map plot

```{r}
x11()
ggplot(data = world1) +
  geom_sf(aes(fill = value)) +
  coord_sf(datum = target_crs, expand = FALSE, clip = "off") +
  scale_fill_distiller(name = "Emissions in 2100\n(GtonCO2)", palette ="RdYlGn", direction=-1) +
  theme_void() + 
  theme(legend.position = "bottom",
        strip.text.x = element_text(size = 12, face="bold")) +
  facet_wrap(~scen, nrow=2)
```
